# Generated by Django 4.1 on 2022-09-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=255)),
                ('release_date', models.TextField()),
                ('watched', models.TextField()),
                ('movie_rating', models.IntegerField()),
                ('movie_review', models.TextField()),
            ],
        ),
    ]
